# Generated by Django 5.0.3 on 2024-04-18 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bigshow', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuario',
        ),
    ]
